language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install unittest  # Replace with the name of your requirements file if you have one

script:
  - python -m unittest discover tests